vim.api.nvim_create_user_command("ChatGPT", function()
  require("chatgpt").openChat()
end, {})
vim.api.nvim_create_user_command("ChatGPTActAs", function()
  require("chatgpt").selectAwesomePrompt()
end, {})
